### ISSUE TITLE
Lag time

### ISSUE THREAD

**Issue by NathanD87** [nforwood/iRadiate#10]
Since iRadiate 2.0 has been implemented, each step is taking a few seconds.

I.e. when injecting a dose
Click Inj' button -> 3-4 sec -> opens
complete window
Click save -> 3-4 sec -> closes

**Comment by nforwood** [comment]
That's a valid point. The routines for loading new screens and saving have been changed so we might be experiencing some slow down there. I will look into the possibility of using asynchronous techniques so that everything appears to chug along.

**Comment by nforwood** [comment]
The lag seems to be significant when the application is periodically requerying the database in the background. The problem is even more acute on the computer in Hot lab because it has very low specs.

**Comment by nforwood** [comment]
In commit b43ca32 I have moved the reloading to a manual, UI blocking, process by default. This should make the app more responsive. Ideally it should also auto reload after 5 minutes of idle time

**Comment by nforwood** [comment]
In commit `1048815` the autodetect changes flag has been switched off during reloads and that seems to have resolved the issue.
